app = "war-frontend"
primary_region = "iad"

[build]
  dockerfile = "apps/frontend/Dockerfile.prod"

[env]
  NUXT_HOST = "0.0.0.0"
  NUXT_PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
